
// ========================================= USER ==================================== //
### register
POST http://localhost:8000/api/users/register
Content-Type: application/json

{

    "username": "pariwesh",
    "email": "user@example.com",
    "password": "C.ronaldo7"
}

### Login User
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "C.ronaldo7"
}

### delete user
DELETE http://localhost:8000/api/users/62522131c954215d69533606

### get user
GET http://localhost:8000/api/users/62526c796664540e248e39a7

### Update user
PUT http://localhost:8000/api/users/62522131c954215d69533606/
Content-Type: : application/json

{
    "userId": "62522131c954215d69533606",
    "isAdmi": "false",
    "description": "Hello"
}

### follow a user
PUT http://localhost:8000/api/users/62552cb46664540e248e39d5/follow
Content-Type: application/json

{
    "userId": "62526c796664540e248e39a7"
}

### unfollow a user
PUT http://localhost:8000/api/users/62526c796664540e248e39a7/unfollow
Content-Type: application/json

{
    "userId": "62566f6372a28f34312b89a0"
}

// =============================================== POST =============================================== //
### create post
POST http://localhost:8000/api/posts
Content-Type: application/json

{
    "userId": "62526c796664540e248e39a7",
    "description": "This is first post from Pariwesh",
    "img": "post/1.jpeg"
}

### update post
PUT http://localhost:8000/api/posts/62522131c954215d69533606
Content-Type: application/json

{
    "userId": "6250275605a33279a9d8fb49",
    "description": "This is a post from Pariwesh"
}

### delete post
DELETE http://localhost:8000/api/posts/62522131c954215d69533606
Content-Type: application/json

{
    "userId": "6250275605a33279a9d8fb49"
}

### like/unlike post
PUT http://localhost:8000/api/posts/62553d8d0d18fef1ec55649b/like
Content-Type: application/json

{
    "userId": "62566f6372a28f34312b89a0"
}
### get post
GET http://localhost:8000/api/posts/6250c165bedfcb7f28ba37ce/

### get timeline posts
GET http://localhost:8000/api/posts/timeline/62566f6372a28f34312b89a0
Content-Type: application/json

{
    "userId": "62566f6372a28f34312b89a0"
}


