### register

POST http://localhost:8000/api/users/register
Content-Type: application/json

{
    "firstName": "Prerana",
    "lastName": "Tamrakar",
    "username": "prerana04",
    "email": "user2@example.com",
    "password": "C.ronaldo7"
}

### Login User
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "username": "pariwesh7",
    "password": "C.ronaldo7"
}

### delete user
DELETE http://localhost:8000/api/users/6250275605a33279a9d8fb49

### get user
GET http://localhost:8000/api/users/6250275605a33279a9d8fb49

### Update user
PUT http://localhost:8000/api/users/6250275605a33279a9d8fb49/
Content-Type: : application/json

{
    "description": "asdasdasdsd"
}

### follow a user
PUT http://localhost:8000/api/users/62502a547f1d5fd530486e25/follow
Content-Type: application/json

{
    "userId": "6250275605a33279a9d8fb49"
}

### unfollow a user
PUT http://localhost:8000/api/users/62502a547f1d5fd530486e25/unfollow
Content-Type: application/json

{
    "userId": "6250275605a33279a9d8fb49"
}

